name: auto write readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"

permissions: write-all

jobs:
  sync-daily:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: write
        run: node dist/index.js ${{ github.token }}

      - name: Compare files
        id: compare
        run: |
          if diff README.md README.md.bak > /dev/null ; then
            echo "Same"
            echo "result=0" >> $GITHUB_OUTPUT
          else
            echo "Different, will update"
            echo "result=1" >> $GITHUB_OUTPUT
          fi

      - name: Commit files
        if: ${{steps.compare.outputs.result == 1}}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "auto update README.md"

      - name: Push changes
        if: ${{steps.compare.outputs.result == 1}}
        uses: ad-m/github-push-action@master
        with: 
          branch: main
          github_token: ${{ github.token }}
